# The name of this GH action 
name: Import

on:
  repository_dispatch:
    types: 
      - release

env:
  CONTENT_REPO: "https://github.com/box/developer.box.com.git#en"

jobs:
  import:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: jungwinter/split@v1
        id: split
        with:
          msg: ${{ github.event.client_payload.ref }}
          seperator: "/"

      - name: Fetch the new release note
        env:
          TAG: ${{ steps.split.outputs._2 }}
          REPOSITORY: ${{ github.event.client_payload.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAGS: ${{ github.event.client_payload.tags }}
          TEMPLATE: ${{ github.event.client_payload.template }}
        run: |
          yarn install
          yarn import:release
      
      - name: Lint the new content
        run: |
          yarn test

      - name: Create a new Pull Request
        uses: peter-evans/create-pull-request@v2
        if: ${{ failure() }}
        with:
          commit-message: '@${{github.event.client_payload.repository}} ${{steps.split.outputs._2}} release note'
          title: '@${{github.event.client_payload.repository}} ${{steps.split.outputs._2}} release note'
          body: 'Automated pull request for @${{github.event.client_payload.repository}} ${{steps.split.outputs._2}} release note'
          branch: "${{github.event.client_payload.repository}}/${{steps.split.outputs._2}}"
          author: 'Box DevRel <devrel@box.com>'
      
      - uses: EndBug/add-and-commit@v4 
        if: ${{ success() }}
        with:
          author_name: Box DevRel
          author_email: mail@example.com
          message: '@${{github.event.client_payload.repository}} ${{steps.split.outputs._2}} release note'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: Send Slack notification
        uses: Ilshidur/action-slack@2.0.2
        if: ${{ always() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GitHub Actions
          SLACK_AVATAR: "https://avatars3.githubusercontent.com/u/8659759?s=200&v=4"
        with:
          args: "@box/box-developer-changelog: @${{ github.event.client_payload.repository }} ${{steps.split.outputs._2}} released"
          