# The name of this GH action 
name: Import

on:
  repository_dispatch:
    types: 
      - release

jobs:
  import:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Send Slack notification
      uses: Ilshidur/action-slack@2.0.2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: GitHub Actions
        SLACK_AVATAR: "https://avatars3.githubusercontent.com/u/8659759?s=200&v=4"
      with:
        args: "@box/box-developer-changelog received an update for version ${{ github.event.client_payload.version }} from @${{ github.event.client_payload.repository }}"
