# This workflow listens to new pushes to 
# the main and staging branches, as well as
# pull requests to those branches. 
#
# It then runs all our tests for the content compilers
# to make sure content is still compiled from source
# markdown correctly

name: Tests

on:
  push: 
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # First check out the repo
      - name: Check out the repo
        uses: actions/checkout@v2

      # Then make sure all tests pass
      - name: Test compiler
        run: |
          yarn install
          yarn test